version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: erudio-spring-boot
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: erudio-spring-boot
      MYSQL_DATABASE: erudio-spring-boot
      MYSQL_USER: erudio-spring-boot
      MYSQL_PASSWORD: erudio-spring-boot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
